services:
  - type: web
    name: nrgflow-backend
    env: node
    nodeVersion: 18
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    buildFilter:
      paths:
        - src/**/*.ts
        - package*.json
        - tsconfig.json 